### ISSUE TITLE
font-family

### ISSUE THREAD

**Issue by ssnaip8e** [illicchpv/band-Tenloc#1]
Почему у тебя шрифты в общем .scss?
Если для удобства поместил бы в отдельный файл, например fonts.scss

**Comment by illicchpv** [comment]
решил не плодить

**Comment by ssnaip8e** [comment]
Каким приложением пользовался, что так раскидало код?

**Comment by illicchpv** [comment]
не понял о чем ты. пользуюсь visual studio code

**Comment by ssnaip8e** [comment]
Нет. Я про семейство шрифтов. Откуда взял эти строчки?

Да, ещё забавно ты классы назначил семейству-шрифтов.
